### ISSUE TITLE
SP時にEmbedがデカすぎる

### ISSUE THREAD

**Issue by dsk52** [d-kusk/my-blog-theme#12]
## 現状

SP 時にiframeの大きさが変わらないのではみ出しちゃう問題が起こっている

<img width="520" alt="2016-07-16 12 04 14" src="https://cloud.githubusercontent.com/assets/8408838/16892501/75a8ce72-4b4f-11e6-867d-6bd8e9accdf2.png">
## Embed が iframe でできてるからちょっと厄介だけど、多分以下で対応できる

``` css
.iframe-content {
    position: relative;
    width: 100%;
    padding: 75% 0 0 0;
}
.iframe-content iframe {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
}
```

[iframe要素のレスポンシブWebデザイン対応 ｜ Tips Note by TAM](http://www.tam-tam.co.jp/tipsnote/html_css/post5074.html)
